package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class CollocItems {
	protected transient boolean swigCMemOwn;
	private transient long swigCPtr;

	protected CollocItems(long cPtr, boolean cMemoryOwn) {
		this.swigCMemOwn = cMemoryOwn;
		this.swigCPtr = cPtr;
	}

	public CollocItems(Concordance conc, String attr_name, char sort_fun_code, long minfreq, long minbgr, int fromw,
			int tow, int maxitems) {
		this(manateeJNI.new_CollocItems(Concordance.getCPtr(conc), conc, attr_name, sort_fun_code, minfreq, minbgr,
				fromw, tow, maxitems), true);
	}

	protected static long getCPtr(CollocItems obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_CollocItems(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
	}

	public boolean eos() {
		return manateeJNI.CollocItems_eos(this.swigCPtr, this);
	}

	@Override
	protected void finalize() {
		this.delete();
	}

	public double get_bgr(char bgr_code) {
		return manateeJNI.CollocItems_get_bgr(this.swigCPtr, this, bgr_code);
	}

	public long get_cnt() {
		return manateeJNI.CollocItems_get_cnt(this.swigCPtr, this);
	}

	public long get_freq() {
		return manateeJNI.CollocItems_get_freq(this.swigCPtr, this);
	}

	public String get_item() {
		return manateeJNI.CollocItems_get_item(this.swigCPtr, this);
	}

	public void next() {
		manateeJNI.CollocItems_next(this.swigCPtr, this);
	}

}
