package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class Concordance {
	protected transient boolean swigCMemOwn;
	private transient long swigCPtr;

	protected Concordance(long cPtr, boolean cMemoryOwn) {
		this.swigCMemOwn = cMemoryOwn;
		this.swigCPtr = cPtr;
	}

	public Concordance() {
		this(manateeJNI.new_Concordance__SWIG_0(), true);
	}

	public Concordance(Corpus corp, String filename) {
		this(manateeJNI.new_Concordance__SWIG_1(Corpus.getCPtr(corp), corp, filename), true);
	}

	public Concordance(Corpus corp, int fileno) {
		this(manateeJNI.new_Concordance__SWIG_2(Corpus.getCPtr(corp), corp, fileno), true);
	}

	public Concordance(Corpus corp, RangeStream rs, int inccoll) {
		this(manateeJNI.new_Concordance__SWIG_3(Corpus.getCPtr(corp), corp, RangeStream.getCPtr(rs), rs, inccoll),
				true);
	}

	public Concordance(Corpus corp, RangeStream rs) {
		this(manateeJNI.new_Concordance__SWIG_4(Corpus.getCPtr(corp), corp, RangeStream.getCPtr(rs), rs), true);
	}

	public Concordance(Concordance x) {
		this(manateeJNI.new_Concordance__SWIG_5(Concordance.getCPtr(x), x), true);
	}

	public Concordance(Corpus corp, String query, int sample_size, long full_size, int inccoll) {
		this(manateeJNI.new_Concordance__SWIG_6(Corpus.getCPtr(corp), corp, query, sample_size, full_size, inccoll),
				true);
	}

	public Concordance(Corpus corp, String query, int sample_size, long full_size) {
		this(manateeJNI.new_Concordance__SWIG_7(Corpus.getCPtr(corp), corp, query, sample_size, full_size), true);
	}

	public Concordance(Corpus corp, FastStream fs, int inccoll) {
		this(manateeJNI.new_Concordance__SWIG_8(Corpus.getCPtr(corp), corp, FastStream.getCPtr(fs), fs, inccoll), true);
	}

	public Concordance(Corpus corp, FastStream fs) {
		this(manateeJNI.new_Concordance__SWIG_9(Corpus.getCPtr(corp), corp, FastStream.getCPtr(fs), fs), true);
	}

	protected static long getCPtr(Concordance obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	public RangeStream RS(boolean useview, int beg, int end) {
		long cPtr = manateeJNI.Concordance_RS__SWIG_0(this.swigCPtr, this, useview, beg, end);
		return (cPtr == 0) ? null : new RangeStream(cPtr, true);
	}

	public RangeStream RS(boolean useview, int beg) {
		long cPtr = manateeJNI.Concordance_RS__SWIG_1(this.swigCPtr, this, useview, beg);
		return (cPtr == 0) ? null : new RangeStream(cPtr, true);
	}

	public RangeStream RS(boolean useview) {
		long cPtr = manateeJNI.Concordance_RS__SWIG_2(this.swigCPtr, this, useview);
		return (cPtr == 0) ? null : new RangeStream(cPtr, true);
	}

	public RangeStream RS() {
		long cPtr = manateeJNI.Concordance_RS__SWIG_3(this.swigCPtr, this);
		return (cPtr == 0) ? null : new RangeStream(cPtr, true);
	}

	public RangeStream RS_using_view() {
		long cPtr = manateeJNI.Concordance_RS_using_view(this.swigCPtr, this);
		return (cPtr == 0) ? null : new RangeStream(cPtr, false);
	}

	public RangeStream RS_using_view_limited(int beg, int end) {
		long cPtr = manateeJNI.Concordance_RS_using_view_limited(this.swigCPtr, this, beg, end);
		return (cPtr == 0) ? null : new RangeStream(cPtr, false);
	}

	public void add_aligned(String corpname) {
		manateeJNI.Concordance_add_aligned(this.swigCPtr, this, corpname);
	}

	public long beg_at(int idx) {
		return manateeJNI.Concordance_beg_at(this.swigCPtr, this, idx);
	}

	public FastStream begs_FS() {
		long cPtr = manateeJNI.Concordance_begs_FS(this.swigCPtr, this);
		return (cPtr == 0) ? null : new FastStream(cPtr, true);
	}

	public long coll_beg_at(int coll, int idx) {
		return manateeJNI.Concordance_coll_beg_at(this.swigCPtr, this, coll, idx);
	}

	public long coll_end_at(int coll, int idx) {
		return manateeJNI.Concordance_coll_end_at(this.swigCPtr, this, coll, idx);
	}

	public double compute_ARF() {
		return manateeJNI.Concordance_compute_ARF(this.swigCPtr, this);
	}

	public Corpus corp() {
		long cPtr = manateeJNI.Concordance_corp(this.swigCPtr, this);
		return (cPtr == 0) ? null : new Corpus(cPtr, false);
	}

	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_Concordance(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
	}

	public void delete_linegroups(String grps, boolean invert) {
		manateeJNI.Concordance_delete_linegroups(this.swigCPtr, this, grps, invert);
	}

	public void delete_pnfilter(int collnum, boolean positive) {
		manateeJNI.Concordance_delete_pnfilter(this.swigCPtr, this, collnum, positive);
	}

	public void delete_struct_repeats(String struc) {
		manateeJNI.Concordance_delete_struct_repeats(this.swigCPtr, this, struc);
	}

	public void delete_subparts() {
		manateeJNI.Concordance_delete_subparts(this.swigCPtr, this);
	}

	public void distribution(IntVector vals, IntVector beginnings, int yrange) {
		manateeJNI.Concordance_distribution(this.swigCPtr, this, IntVector.getCPtr(vals), vals,
				IntVector.getCPtr(beginnings), beginnings, yrange);
	}

	public long end_at(int idx) {
		return manateeJNI.Concordance_end_at(this.swigCPtr, this, idx);
	}

	public void extend_kwic_coll(int collnum) {
		manateeJNI.Concordance_extend_kwic_coll(this.swigCPtr, this, collnum);
	}

	public void filter_aligned(String corpname) {
		manateeJNI.Concordance_filter_aligned(this.swigCPtr, this, corpname);
	}

	@Override
	protected void finalize() {
		this.delete();
	}

	public boolean finished() {
		return manateeJNI.Concordance_finished(this.swigCPtr, this);
	}

	public long fullsize() {
		return manateeJNI.Concordance_fullsize(this.swigCPtr, this);
	}

	public void get_aligned(StrVector aligned) {
		manateeJNI.Concordance_get_aligned(this.swigCPtr, this, StrVector.getCPtr(aligned), aligned);
	}

	public void get_linegroup_stat(IntVector ids, IntVector freqs) {
		manateeJNI.Concordance_get_linegroup_stat(this.swigCPtr, this, IntVector.getCPtr(ids), ids,
				IntVector.getCPtr(freqs), freqs);
	}

	public int get_new_linegroup_id() {
		return manateeJNI.Concordance_get_new_linegroup_id(this.swigCPtr, this);
	}

	public void linegroup_sort(IntVector ids, StrVector strs) {
		manateeJNI.Concordance_linegroup_sort(this.swigCPtr, this, IntVector.getCPtr(ids), ids, StrVector.getCPtr(strs),
				strs);
	}

	public void load_from_file(Corpus corp, String filename) {
		manateeJNI.Concordance_load_from_file(this.swigCPtr, this, Corpus.getCPtr(corp), corp, filename);
	}

	public void load_from_fileno(Corpus corp, int fileno) {
		manateeJNI.Concordance_load_from_fileno(this.swigCPtr, this, Corpus.getCPtr(corp), corp, fileno);
	}

	public void load_from_fs(Corpus corp, FastStream fs, int sample_size, long full_size) {
		manateeJNI.Concordance_load_from_fs(this.swigCPtr, this, Corpus.getCPtr(corp), corp, FastStream.getCPtr(fs), fs,
				sample_size, full_size);
	}

	public void load_from_query(Corpus corp, String query, int sample_size, long full_size) {
		manateeJNI.Concordance_load_from_query(this.swigCPtr, this, Corpus.getCPtr(corp), corp, query, sample_size,
				full_size);
	}

	public void load_from_rs(Corpus corp, RangeStream rs, int sample_size, long full_size) {
		manateeJNI.Concordance_load_from_rs(this.swigCPtr, this, Corpus.getCPtr(corp), corp, RangeStream.getCPtr(rs),
				rs, sample_size, full_size);
	}

	public int numofcolls() {
		return manateeJNI.Concordance_numofcolls(this.swigCPtr, this);
	}

	public void reduce_lines(String crit) {
		manateeJNI.Concordance_reduce_lines(this.swigCPtr, this, crit);
	}

	public void relfreq_sort(String leftctx, String rightctx, String attr) {
		manateeJNI.Concordance_relfreq_sort(this.swigCPtr, this, leftctx, rightctx, attr);
	}

	public void save(String filename, boolean save_linegroup, boolean partial, boolean append) {
		manateeJNI.Concordance_save__SWIG_0(this.swigCPtr, this, filename, save_linegroup, partial, append);
	}

	public void save(String filename, boolean save_linegroup, boolean partial) {
		manateeJNI.Concordance_save__SWIG_1(this.swigCPtr, this, filename, save_linegroup, partial);
	}

	public void save(String filename, boolean save_linegroup) {
		manateeJNI.Concordance_save__SWIG_2(this.swigCPtr, this, filename, save_linegroup);
	}

	public void save(String filename) {
		manateeJNI.Concordance_save__SWIG_3(this.swigCPtr, this, filename);
	}

	public void save(int fileno, boolean save_linegroup, boolean partial, boolean append) {
		manateeJNI.Concordance_save__SWIG_4(this.swigCPtr, this, fileno, save_linegroup, partial, append);
	}

	public void save(int fileno, boolean save_linegroup, boolean partial) {
		manateeJNI.Concordance_save__SWIG_5(this.swigCPtr, this, fileno, save_linegroup, partial);
	}

	public void save(int fileno, boolean save_linegroup) {
		manateeJNI.Concordance_save__SWIG_6(this.swigCPtr, this, fileno, save_linegroup);
	}

	public void save(int fileno) {
		manateeJNI.Concordance_save__SWIG_7(this.swigCPtr, this, fileno);
	}

	public void save_fileno(int fileno, boolean save_linegroup, boolean partial) {
		manateeJNI.Concordance_save_fileno(this.swigCPtr, this, fileno, save_linegroup, partial);
	}

	public void save_with_linegroup(String filename) {
		manateeJNI.Concordance_save_with_linegroup(this.swigCPtr, this, filename);
	}

	public void save_without_linegroup(String filename) {
		manateeJNI.Concordance_save_without_linegroup(this.swigCPtr, this, filename);
	}

	public void set_collocation(int collnum, String cquery, String lctx, String rctx, int rank, boolean exclude_kwic) {
		manateeJNI.Concordance_set_collocation__SWIG_0(this.swigCPtr, this, collnum, cquery, lctx, rctx, rank,
				exclude_kwic);
	}

	public void set_collocation(int collnum, String cquery, String lctx, String rctx, int rank) {
		manateeJNI.Concordance_set_collocation__SWIG_1(this.swigCPtr, this, collnum, cquery, lctx, rctx, rank);
	}

	public void set_linegroup(int linenum, int group) {
		manateeJNI.Concordance_set_linegroup(this.swigCPtr, this, linenum, group);
	}

	public int set_linegroup_at_pos(long pos, int group) {
		return manateeJNI.Concordance_set_linegroup_at_pos(this.swigCPtr, this, pos, group);
	}

	public void set_linegroup_from_conc(Concordance master) {
		manateeJNI.Concordance_set_linegroup_from_conc(this.swigCPtr, this, Concordance.getCPtr(master), master);
	}

	public void set_linegroup_globally(int group) {
		manateeJNI.Concordance_set_linegroup_globally(this.swigCPtr, this, group);
	}

	public void set_sorted_view(IntVector sorted) {
		manateeJNI.Concordance_set_sorted_view(this.swigCPtr, this, IntVector.getCPtr(sorted), sorted);
	}

	public void shuffle() {
		manateeJNI.Concordance_shuffle(this.swigCPtr, this);
	}

	public int size() {
		return manateeJNI.Concordance_size(this.swigCPtr, this);
	}

	public void sort(String crit, boolean uniq) {
		manateeJNI.Concordance_sort__SWIG_0(this.swigCPtr, this, crit, uniq);
	}

	public void sort(String crit) {
		manateeJNI.Concordance_sort__SWIG_1(this.swigCPtr, this, crit);
	}

	public void sort_idx(String crit, StrVector chars, IntVector idxs, boolean firstCharOnly) {
		manateeJNI.Concordance_sort_idx(this.swigCPtr, this, crit, StrVector.getCPtr(chars), chars,
				IntVector.getCPtr(idxs), idxs, firstCharOnly);
	}

	public void swap_kwic_coll(int collnum) {
		manateeJNI.Concordance_swap_kwic_coll(this.swigCPtr, this, collnum);
	}

	public void switch_aligned(String corpname) {
		manateeJNI.Concordance_switch_aligned(this.swigCPtr, this, corpname);
	}

	public void sync() {
		manateeJNI.Concordance_sync(this.swigCPtr, this);
	}

	public int viewsize() {
		return manateeJNI.Concordance_viewsize(this.swigCPtr, this);
	}

}
