package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class CorpInfo {
	protected transient boolean swigCMemOwn;
	private transient long swigCPtr;

	protected CorpInfo(long cPtr, boolean cMemoryOwn) {
		this.swigCMemOwn = cMemoryOwn;
		this.swigCPtr = cPtr;
	}

	public CorpInfo() {
		this(manateeJNI.new_CorpInfo(), true);
	}

	protected static long getCPtr(CorpInfo obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	public CorpInfo add_attr(String path) {
		long cPtr = manateeJNI.CorpInfo_add_attr(this.swigCPtr, this, path);
		return (cPtr == 0) ? null : new CorpInfo(cPtr, false);
	}

	public CorpInfo add_struct(String path) {
		long cPtr = manateeJNI.CorpInfo_add_struct(this.swigCPtr, this, path);
		return (cPtr == 0) ? null : new CorpInfo(cPtr, false);
	}

	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_CorpInfo(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
	}

	public String dump(int indent) {
		return manateeJNI.CorpInfo_dump__SWIG_0(this.swigCPtr, this, indent);
	}

	public String dump() {
		return manateeJNI.CorpInfo_dump__SWIG_1(this.swigCPtr, this);
	}

	@Override
	protected void finalize() {
		this.delete();
	}

	public String find_opt(String path) {
		return manateeJNI.CorpInfo_find_opt(this.swigCPtr, this, path);
	}

	public CorpInfo find_struct(String path) {
		long cPtr = manateeJNI.CorpInfo_find_struct(this.swigCPtr, this, path);
		return (cPtr == 0) ? null : new CorpInfo(cPtr, false);
	}

	public void remove_attr(String path) {
		manateeJNI.CorpInfo_remove_attr(this.swigCPtr, this, path);
	}

	public void remove_struct(String path) {
		manateeJNI.CorpInfo_remove_struct(this.swigCPtr, this, path);
	}

	public void set_opt(String path, String val) {
		manateeJNI.CorpInfo_set_opt(this.swigCPtr, this, path, val);
	}

}
