package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class Corpus {
	protected transient boolean swigCMemOwn;
	private transient long swigCPtr;

	protected Corpus(long cPtr, boolean cMemoryOwn) {
		this.swigCMemOwn = cMemoryOwn;
		this.swigCPtr = cPtr;
	}

	public Corpus(String corp_name) {
		this(manateeJNI.new_Corpus(corp_name), true);
	}

	protected static long getCPtr(Corpus obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	public FastStream Range2Pos(RangeStream r) {
		long cPtr = manateeJNI.Corpus_Range2Pos(this.swigCPtr, this, RangeStream.getCPtr(r), r);
		return (cPtr == 0) ? null : new FastStream(cPtr, false);
	}

	public void compile_aldf(String attr) {
		manateeJNI.Corpus_compile_aldf(this.swigCPtr, this, attr);
	}

	public void compile_arf(String attr) {
		manateeJNI.Corpus_compile_arf(this.swigCPtr, this, attr);
	}

	public void compile_docf(String attr, String docstruc) {
		manateeJNI.Corpus_compile_docf(this.swigCPtr, this, attr, docstruc);
	}

	public void compile_frq(String attr) {
		manateeJNI.Corpus_compile_frq(this.swigCPtr, this, attr);
	}

	public long count_rest(FastStream s) {
		return manateeJNI.Corpus_count_rest(this.swigCPtr, this, FastStream.getCPtr(s), s);
	}

	public void count_structattr_vals(String structname, String saname, boolean docsizes, NumVector freqs) {
		manateeJNI.Corpus_count_structattr_vals(this.swigCPtr, this, structname, saname, docsizes,
				NumVector.getCPtr(freqs), freqs);
	}

	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_Corpus(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
	}

	public RangeStream eval_query(String query) {
		long cPtr = manateeJNI.Corpus_eval_query(this.swigCPtr, this, query);
		return (cPtr == 0) ? null : new RangeStream(cPtr, true);
	}

	public FastStream filter_fstream(FastStream s) {
		long cPtr = manateeJNI.Corpus_filter_fstream(this.swigCPtr, this, FastStream.getCPtr(s), s);
		return (cPtr == 0) ? null : new FastStream(cPtr, true);
	}

	public RangeStream filter_query(RangeStream s) {
		long cPtr = manateeJNI.Corpus_filter_query(this.swigCPtr, this, RangeStream.getCPtr(s), s);
		return (cPtr == 0) ? null : new RangeStream(cPtr, true);
	}

	@Override
	protected void finalize() {
		this.delete();
	}

	public void freq_dist(RangeStream r, String crit, int limit, StrVector words, NumVector freqs, NumVector norms) {
		manateeJNI.Corpus_freq_dist__SWIG_0(this.swigCPtr, this, RangeStream.getCPtr(r), r, crit, limit,
				StrVector.getCPtr(words), words, NumVector.getCPtr(freqs), freqs, NumVector.getCPtr(norms), norms);
	}

	public void freq_dist(FastStream r, String crit, int limit, StrVector words, NumVector freqs, NumVector norms) {
		manateeJNI.Corpus_freq_dist__SWIG_1(this.swigCPtr, this, FastStream.getCPtr(r), r, crit, limit,
				StrVector.getCPtr(words), words, NumVector.getCPtr(freqs), freqs, NumVector.getCPtr(norms), norms);
	}

	public void freq_dist_from_fs(FastStream r, String crit, int limit, StrVector words, NumVector freqs,
			NumVector norms) {
		manateeJNI.Corpus_freq_dist_from_fs(this.swigCPtr, this, FastStream.getCPtr(r), r, crit, limit,
				StrVector.getCPtr(words), words, NumVector.getCPtr(freqs), freqs, NumVector.getCPtr(norms), norms);
	}

	public PosAttr get_attr(String name, boolean struct_attr) {
		long cPtr = manateeJNI.Corpus_get_attr__SWIG_0(this.swigCPtr, this, name, struct_attr);
		return (cPtr == 0) ? null : new PosAttr(cPtr, false);
	}

	public PosAttr get_attr(String name) {
		long cPtr = manateeJNI.Corpus_get_attr__SWIG_1(this.swigCPtr, this, name);
		return (cPtr == 0) ? null : new PosAttr(cPtr, false);
	}

	public String get_conf(String item) {
		return manateeJNI.Corpus_get_conf(this.swigCPtr, this, item);
	}

	public String get_conffile() {
		return manateeJNI.Corpus_get_conffile(this.swigCPtr, this);
	}

	public String get_confpath() {
		return manateeJNI.Corpus_get_confpath(this.swigCPtr, this);
	}

	public String get_info() {
		return manateeJNI.Corpus_get_info(this.swigCPtr, this);
	}

	public String get_sizes() {
		return manateeJNI.Corpus_get_sizes(this.swigCPtr, this);
	}

	public Structure get_struct(String name) {
		long cPtr = manateeJNI.Corpus_get_struct(this.swigCPtr, this, name);
		return (cPtr == 0) ? null : new Structure(cPtr, false);
	}

	public PosAttr get_struct_attr(String name) {
		long cPtr = manateeJNI.Corpus_get_struct_attr(this.swigCPtr, this, name);
		return (cPtr == 0) ? null : new PosAttr(cPtr, false);
	}

	public long search_size() {
		return manateeJNI.Corpus_search_size(this.swigCPtr, this);
	}

	public void set_default_attr(String attname) {
		manateeJNI.Corpus_set_default_attr(this.swigCPtr, this, attname);
	}

	public void set_reference_corpus(String refcorp) {
		manateeJNI.Corpus_set_reference_corpus(this.swigCPtr, this, refcorp);
	}

	public long size() {
		return manateeJNI.Corpus_size(this.swigCPtr, this);
	}

}
