package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class FastStream {
	protected transient boolean swigCMemOwn;
	private transient long swigCPtr;

	protected FastStream(long cPtr, boolean cMemoryOwn) {
		this.swigCMemOwn = cMemoryOwn;
		this.swigCPtr = cPtr;
	}

	protected static long getCPtr(FastStream obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	public void collocs(IntVector colls) {
		manateeJNI.FastStream_collocs(this.swigCPtr, this, IntVector.getCPtr(colls), colls);
	}

	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_FastStream(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
	}

	public boolean end() {
		return manateeJNI.FastStream_end(this.swigCPtr, this);
	}

	@Override
	protected void finalize() {
		this.delete();
	}

	public long find(long pos) {
		return manateeJNI.FastStream_find(this.swigCPtr, this, pos);
	}

	public long next() {
		return manateeJNI.FastStream_next(this.swigCPtr, this);
	}

	public long peek() {
		return manateeJNI.FastStream_peek(this.swigCPtr, this);
	}

}
