package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class FileAccessError {
	protected transient boolean swigCMemOwn;
	private transient long swigCPtr;

	protected FileAccessError(long cPtr, boolean cMemoryOwn) {
		this.swigCMemOwn = cMemoryOwn;
		this.swigCPtr = cPtr;
	}

	public FileAccessError(String filename, String where) {
		this(manateeJNI.new_FileAccessError(filename, where), true);
	}

	protected static long getCPtr(FileAccessError obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	public String __str__() {
		return manateeJNI.FileAccessError___str__(this.swigCPtr, this);
	}

	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_FileAccessError(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
	}

	@Override
	protected void finalize() {
		this.delete();
	}

}
