package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class IDIterator {
	protected transient boolean swigCMemOwn;
	private transient long swigCPtr;

	protected IDIterator(long cPtr, boolean cMemoryOwn) {
		this.swigCMemOwn = cMemoryOwn;
		this.swigCPtr = cPtr;
	}

	protected static long getCPtr(IDIterator obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	public int __getitem__(int array_index) {
		return manateeJNI.IDIterator___getitem__(this.swigCPtr, this, array_index);
	}

	public int __len__() {
		return manateeJNI.IDIterator___len__(this.swigCPtr, this);
	}

	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_IDIterator(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
	}

	@Override
	protected void finalize() {
		this.delete();
	}

	public int next() {
		return manateeJNI.IDIterator_next(this.swigCPtr, this);
	}

}
