package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class map_int_sort_bigrams {
	protected transient boolean swigCMemOwn;
	private transient long swigCPtr;

	protected map_int_sort_bigrams(long cPtr, boolean cMemoryOwn) {
		this.swigCMemOwn = cMemoryOwn;
		this.swigCPtr = cPtr;
	}

	public map_int_sort_bigrams(String filename) {
		this(manateeJNI.new_map_int_sort_bigrams(filename), true);
	}

	protected static long getCPtr(map_int_sort_bigrams obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	public int count(int id) {
		return manateeJNI.map_int_sort_bigrams_count(this.swigCPtr, this, id);
	}

	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_map_int_sort_bigrams(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
	}

	@Override
	protected void finalize() {
		this.delete();
	}

	public int maxid() {
		return manateeJNI.map_int_sort_bigrams_maxid(this.swigCPtr, this);
	}

	public int value(int id1, int id2) {
		return manateeJNI.map_int_sort_bigrams_value(this.swigCPtr, this, id1, id2);
	}

}
