package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class PosAttr {
	protected transient boolean swigCMemOwn;
	private transient long swigCPtr;

	protected PosAttr(long cPtr, boolean cMemoryOwn) {
		this.swigCMemOwn = cMemoryOwn;
		this.swigCPtr = cPtr;
	}

	protected static long getCPtr(PosAttr obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	public float aldf(int id) {
		return manateeJNI.PosAttr_aldf(this.swigCPtr, this, id);
	}

	public float arf(int id) {
		return manateeJNI.PosAttr_arf(this.swigCPtr, this, id);
	}

	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_PosAttr(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
	}

	public long docf(int id) {
		return manateeJNI.PosAttr_docf(this.swigCPtr, this, id);
	}

	public FastStream dynid2srcids(int id) {
		long cPtr = manateeJNI.PosAttr_dynid2srcids(this.swigCPtr, this, id);
		return (cPtr == 0) ? null : new FastStream(cPtr, true);
	}

	@Override
	protected void finalize() {
		this.delete();
	}

	public long freq(int id) {
		return manateeJNI.PosAttr_freq(this.swigCPtr, this, id);
	}

	public String getName() {
		return manateeJNI.PosAttr_name_get(this.swigCPtr, this);
	}

	public FastStream id2poss(int id) {
		long cPtr = manateeJNI.PosAttr_id2poss(this.swigCPtr, this, id);
		return (cPtr == 0) ? null : new FastStream(cPtr, true);
	}

	public String id2str(int id) {
		return manateeJNI.PosAttr_id2str(this.swigCPtr, this, id);
	}

	public int id_range() {
		return manateeJNI.PosAttr_id_range(this.swigCPtr, this);
	}

	public long norm(int id) {
		return manateeJNI.PosAttr_norm(this.swigCPtr, this, id);
	}

	public int pos2id(long pos) {
		return manateeJNI.PosAttr_pos2id(this.swigCPtr, this, pos);
	}

	public String pos2str(long pos) {
		return manateeJNI.PosAttr_pos2str(this.swigCPtr, this, pos);
	}

	public IDIterator posat(long pos) {
		long cPtr = manateeJNI.PosAttr_posat(this.swigCPtr, this, pos);
		return (cPtr == 0) ? null : new IDIterator(cPtr, true);
	}

	public IntGenerator regexp2ids(String pat, boolean ignorecase, String filter_pat) {
		long cPtr = manateeJNI.PosAttr_regexp2ids__SWIG_0(this.swigCPtr, this, pat, ignorecase, filter_pat);
		return (cPtr == 0) ? null : new IntGenerator(cPtr, true);
	}

	public IntGenerator regexp2ids(String pat, boolean ignorecase) {
		long cPtr = manateeJNI.PosAttr_regexp2ids__SWIG_1(this.swigCPtr, this, pat, ignorecase);
		return (cPtr == 0) ? null : new IntGenerator(cPtr, true);
	}

	public IntGenerator regexp2ids_filtered(String pat, String filter_pat) {
		long cPtr = manateeJNI.PosAttr_regexp2ids_filtered(this.swigCPtr, this, pat, filter_pat);
		return (cPtr == 0) ? null : new IntGenerator(cPtr, true);
	}

	public FastStream regexp2poss(String pat, boolean ignorecase) {
		long cPtr = manateeJNI.PosAttr_regexp2poss(this.swigCPtr, this, pat, ignorecase);
		return (cPtr == 0) ? null : new FastStream(cPtr, true);
	}

	public long size() {
		return manateeJNI.PosAttr_size(this.swigCPtr, this);
	}

	public int str2id(String str) {
		return manateeJNI.PosAttr_str2id(this.swigCPtr, this, str);
	}

	public TextIterator textat(long pos) {
		long cPtr = manateeJNI.PosAttr_textat(this.swigCPtr, this, pos);
		return (cPtr == 0) ? null : new TextIterator(cPtr, true);
	}

}
