package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class RangeStream {
	protected transient boolean swigCMemOwn;
	private transient long swigCPtr;

	protected RangeStream(long cPtr, boolean cMemoryOwn) {
		this.swigCMemOwn = cMemoryOwn;
		this.swigCPtr = cPtr;
	}

	protected static long getCPtr(RangeStream obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	public void collocs(IntVector colls) {
		manateeJNI.RangeStream_collocs(this.swigCPtr, this, IntVector.getCPtr(colls), colls);
	}

	public long count_rest() {
		return manateeJNI.RangeStream_count_rest(this.swigCPtr, this);
	}

	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_RangeStream(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
	}

	public boolean end() {
		return manateeJNI.RangeStream_end(this.swigCPtr, this);
	}

	@Override
	protected void finalize() {
		this.delete();
	}

	public long find_beg(long pos) {
		return manateeJNI.RangeStream_find_beg(this.swigCPtr, this, pos);
	}

	public long find_end(long pos) {
		return manateeJNI.RangeStream_find_end(this.swigCPtr, this, pos);
	}

	public boolean next() {
		return manateeJNI.RangeStream_next(this.swigCPtr, this);
	}

	public long peek_beg() {
		return manateeJNI.RangeStream_peek_beg(this.swigCPtr, this);
	}

	public long peek_end() {
		return manateeJNI.RangeStream_peek_end(this.swigCPtr, this);
	}

}
