package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class Structure {
	protected transient boolean swigCMemOwn;
	private transient long swigCPtr;

	protected Structure(long cPtr, boolean cMemoryOwn) {
		this.swigCMemOwn = cMemoryOwn;
		this.swigCPtr = cPtr;
	}

	protected static long getCPtr(Structure obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	public RangeStream attr_val(String aname, int attr_id) {
		long cPtr = manateeJNI.Structure_attr_val(this.swigCPtr, this, aname, attr_id);
		return (cPtr == 0) ? null : new RangeStream(cPtr, true);
	}

	public long beg(long n) {
		return manateeJNI.Structure_beg(this.swigCPtr, this, n);
	}

	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_Structure(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
	}

	public long end(long n) {
		return manateeJNI.Structure_end(this.swigCPtr, this, n);
	}

	@Override
	protected void finalize() {
		this.delete();
	}

	public String getName() {
		return manateeJNI.Structure_name_get(this.swigCPtr, this);
	}

	public PosAttr get_attr(String attr_name) {
		long cPtr = manateeJNI.Structure_get_attr(this.swigCPtr, this, attr_name);
		return (cPtr == 0) ? null : new PosAttr(cPtr, false);
	}

	public long num_at_pos(long pos) {
		return manateeJNI.Structure_num_at_pos(this.swigCPtr, this, pos);
	}

	public long num_next_pos(long pos) {
		return manateeJNI.Structure_num_next_pos(this.swigCPtr, this, pos);
	}

	public long size() {
		return manateeJNI.Structure_size(this.swigCPtr, this);
	}

	public RangeStream whole() {
		long cPtr = manateeJNI.Structure_whole(this.swigCPtr, this);
		return (cPtr == 0) ? null : new RangeStream(cPtr, true);
	}

}
