package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class StrVector {
	protected transient boolean swigCMemOwn;
	private transient long swigCPtr;

	protected StrVector(long cPtr, boolean cMemoryOwn) {
		this.swigCMemOwn = cMemoryOwn;
		this.swigCPtr = cPtr;
	}

	public StrVector() {
		this(manateeJNI.new_StrVector__SWIG_0(), true);
	}

	public StrVector(long n) {
		this(manateeJNI.new_StrVector__SWIG_1(n), true);
	}

	protected static long getCPtr(StrVector obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	public void add(String x) {
		manateeJNI.StrVector_add(this.swigCPtr, this, x);
	}

	public long capacity() {
		return manateeJNI.StrVector_capacity(this.swigCPtr, this);
	}

	public void clear() {
		manateeJNI.StrVector_clear(this.swigCPtr, this);
	}

	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_StrVector(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
	}

	@Override
	protected void finalize() {
		this.delete();
	}

	public String get(int i) {
		return manateeJNI.StrVector_get(this.swigCPtr, this, i);
	}

	public boolean isEmpty() {
		return manateeJNI.StrVector_isEmpty(this.swigCPtr, this);
	}

	public void reserve(long n) {
		manateeJNI.StrVector_reserve(this.swigCPtr, this, n);
	}

	public void set(int i, String val) {
		manateeJNI.StrVector_set(this.swigCPtr, this, i, val);
	}

	public long size() {
		return manateeJNI.StrVector_size(this.swigCPtr, this);
	}

}
