package com.sketchengine.manatee;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class SubCorpus extends Corpus {
	private transient long swigCPtr;

	protected SubCorpus(long cPtr, boolean cMemoryOwn) {
		super(manateeJNI.SubCorpus_SWIGUpcast(cPtr), cMemoryOwn);
		this.swigCPtr = cPtr;
	}

	public SubCorpus(Corpus corp, String sub, boolean complement) {
		this(manateeJNI.new_SubCorpus__SWIG_0(Corpus.getCPtr(corp), corp, sub, complement), true);
	}

	public SubCorpus(Corpus corp, String sub) {
		this(manateeJNI.new_SubCorpus__SWIG_1(Corpus.getCPtr(corp), corp, sub), true);
	}

	protected static long getCPtr(SubCorpus obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	@Override
	public synchronized void delete() {
		if (this.swigCPtr != 0) {
			if (this.swigCMemOwn) {
				this.swigCMemOwn = false;
				manateeJNI.delete_SubCorpus(this.swigCPtr);
			}
			this.swigCPtr = 0;
		}
		super.delete();
	}

	@Override
	protected void finalize() {
		this.delete();
	}

}
