#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3-amazoncorretto-11

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
  branches:
    master:
      - step:
          name: Deploy to production
          deployment: production
          caches:
            - maven
          script:
            - mvn clean compile package
            - pipe: atlassian/scp-deploy:1.2.1
              variables:
                USER: 'drwolf'
                SERVER: 'impaqts-be.cloudvm.it'
                REMOTE_PATH: '/home/drwolf/wrapper/ImpaqtsWrapper-jar-with-dependencies.jar'
                LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/target/ImpaqtsWrapper-jar-with-dependencies.jar'
        